import { NextRequest, NextResponse } from 'next/server';
import { getAuthUser, isAdmin } from '@/lib/auth-server';

// Support both specific and project-wide aliases for the Gemini API key
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || process.env.NANOBANANA_API_KEY;

export async function POST(request: NextRequest) {
    try {
        const decodedToken = await getAuthUser(request);
        if (!decodedToken) return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
        
        const admin = await isAdmin(decodedToken.uid);
        if (!admin) return NextResponse.json({ success: false, error: 'Access denied' }, { status: 403 });

        const { description } = await request.json();
        if (!description) return NextResponse.json({ success: false, error: 'Description is required' }, { status: 400 });

        if (!GEMINI_API_KEY) {
            return NextResponse.json({ 
                success: false, 
                error: 'AI architect is not configured (missing GEMINI_API_KEY).' 
            }, { status: 500 });
        }

        // Professional image generation engineering prompt targeting Imagen 3 / Midjourney style
        const prompt = `Act as a professional Image Generation Prompt Engineer. 
Produce a high-fidelity, visually stunning prompt for a resource thumbnail image.
The thumbnail is for a platform called "Stillwater" and is inspired by the "Nanobanana" aesthetic (clean, modern, vibrant, tech-focused).

Description of the scenario: "${description}"

Constraint: The prompt should be optimized for NanoBanana/Imagen. Focus on lighting, composition (Rule of Thirds), color palette (Stillwater Blue/Indigo/Purple), and texture. Use descriptive, evocative language.

Reply ONLY with the engineered prompt string. No conversational text.`;

        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{ parts: [{ text: prompt }] }],
                generationConfig: {
                    temperature: 0.7,
                    maxOutputTokens: 256,
                }
            })
        });

        const data = await response.json();
        
        if (!response.ok) {
            throw new Error(data.error?.message || 'Gemini API returned an error.');
        }

        const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim()?.replace(/^"|"$/g, '');

        if (!generatedText) {
            throw new Error('No prompt generated by AI.');
        }

        return NextResponse.json({ 
            success: true, 
            prompt: generatedText 
        });

    } catch (error: any) {
        console.error('Scenario Generation Error:', error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
