import {
    Loader2,
    Download,
    Trash2,
    Copy,
    Share2,
    ExternalLink,
    MoreHorizontal,
    Heart,
    MessageSquare,
    Repeat,
    Flag,
    UserPlus,
    UserCheck,
    Trophy,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    Plus,
    Search,
    Settings,
    Image as ImageIcon,
    History,
    LayoutGrid,
    Layers,
    Check,
    X,
    AlertCircle,
    Clock,
    ArrowLeft,
    ArrowRight,
    Sparkles,
    Zap,
    CreditCard,
    LogOut,
    User,
    Home,
    Bell,
    Menu,
    Eye,
    EyeOff,
    Filter,
    Video,
    ArrowUp,
    ArrowDown,
    Info,
    Globe,
    HardDrive,
    AlertTriangle,
    Activity,
    Wand2,
    Shield,
    Upload,
    FileText,
    List,
    LayoutList,
    Users,
    Rows,
    Tag,
    Play,
    Award,
    RefreshCw
} from "lucide-react"

// Twitter/X icon (removed from lucide-react v1)
const Twitter = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" fill="currentColor" width="1em" height="1em" {...props}>
        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.746l7.73-8.835L1.254 2.25H8.08l4.253 5.622L18.244 2.25zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77z"/>
    </svg>
);

// Instagram icon (removed from lucide-react v1)
const Instagram = (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" width="1em" height="1em" {...props}>
        <rect width="20" height="20" x="2" y="2" rx="5" ry="5"/>
        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/>
        <line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/>
    </svg>
);

export const Icons = {
    play: Play,
    tag: Tag,
    instagram: Instagram,

    spinner: Loader2,
    users: Users,
    wand: Wand2,
    text: FileText,
    upload: Upload,
    download: Download,
    delete: Trash2,
    copy: Copy,
    share: Share2,
    twitter: Twitter,
    external: ExternalLink,
    more: MoreHorizontal,
    heart: Heart,
    comment: MessageSquare,
    variation: Repeat,
    report: Flag,
    follow: UserPlus,
    following: UserCheck,
    trophy: Trophy,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    plus: Plus,
    search: Search,
    settings: Settings,
    image: ImageIcon,
    history: History,
    grid: LayoutGrid,
    stack: Layers,
    check: Check,
    close: X,
    clock: Clock,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    sparkles: Sparkles,
    zap: Zap,
    billing: CreditCard,
    logout: LogOut,
    user: User,
    home: Home,
    bell: Bell,
    menu: Menu,
    eye: Eye,
    eyeOff: EyeOff,
    filter: Filter,
    video: Video,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    info: Info,
    globe: Globe,
    database: HardDrive,
    alert: AlertTriangle,
    activity: Activity,
    shield: Shield,
    error: AlertTriangle,
    list: List,
    feed: LayoutList,
    rows: Rows,
    exemplar: Award,
    refresh: RefreshCw
}
